//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2016.04.12 at 07:50:56 PM CAT
//

package io.vandam.dbdeploy.databasestructure;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

@XmlType(name = "columnType")
@XmlEnum
public enum ColumnType {

    /**
     * The char.
     */
    CHAR,

    /**
     * The date.
     */
    DATE,

    /**
     * The decimal.
     */
    DECIMAL,

    /**
     * 32bit integer
     */
    INTEGER,

    /**
     * 64bit integer
     */
    BIGINT,

    /**
     * The time.
     */
    TIME,

    /**
     * The timestamp.
     */
    TIMESTAMP,

    /**
     * The varchar.
     */
    VARCHAR;

    /**
     * From value.
     *
     * @param v the v
     * @return the column type
     */
    public static ColumnType fromValue(final String v) {
        return valueOf(v.toUpperCase());
    }

    /**
     * Value.
     *
     * @return the string
     */
    public String value() {
        return name();
    }
}
