//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.11
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2016.04.12 at 07:50:56 PM CAT
//

package io.vandam.dbdeploy.databasestructure;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "foreignKey", propOrder = {"name", "column", "referenceTable", "referenceColumn"})
public class ForeignKey {

    @XmlElement(required = true)
    private String name;

    @XmlElement(required = true)
    private List<String> column;

    @XmlElement(required = true)
    private String referenceTable;

    @XmlElement(required = true)
    private List<String> referenceColumn;

    /**
     * Gets the value of the name property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setName(final String value) {
        name = value;
    }

    /**
     * Gets the value of the columns property.
     *
     * @return possible object is
     */
    public List<String> getColumns() {
        if (null == column) {
            column = new ArrayList<>();
        }

        return column;
    }

    /**
     * Gets the value of the referenceTable property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getReferenceTable() {
        return referenceTable;
    }

    /**
     * Sets the value of the referenceTable property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setReferenceTable(final String value) {
        referenceTable = value;
    }

    /**
     * Gets the value of the referenceColumns property.
     *
     * @return possible object is
     */
    public List<String> getReferenceColumns() {
        if (null == referenceColumn) {
            referenceColumn = new ArrayList<>();
        }
        return referenceColumn;
    }

    /**
     * Equals.
     *
     * @param obj the other
     * @return true, if successful
     */
    @Override
    public boolean equals(final Object obj) {
        if (null == obj) {
            return false;
        }

        if (!ForeignKey.class.equals(obj.getClass())) {
            return false;
        }

        final ForeignKey other = (ForeignKey) obj;

        boolean resp = (null == name) ? (null == other.name) : name.equals(other.name);
        resp &= (null == column) ? (null == other.column) : column.equals(other.column);
        resp &= (null == referenceTable) ? (null == other.referenceTable) : referenceTable.equals(other.referenceTable);
        resp &= (null == referenceColumn) ? (null == other.referenceColumn) : referenceColumn.equals(other.referenceColumn);
        return resp;
    }

    @Override
    public int hashCode() {
        int result = (null != name) ? name.hashCode() : 0;
        result = (31 * result) + ((null != column) ? column.hashCode() : 0);
        result = (31 * result) + ((null != referenceTable) ? referenceTable.hashCode() : 0);
        result = (31 * result) + ((null != referenceColumn) ? referenceColumn.hashCode() : 0);
        return result;
    }
}
